### ISSUE TITLE
使用cargo qemu进行build时报错

### ISSUE THREAD

**Issue by leo-frank** [rustsbi/rustsbi-qemu#10]
我在使用cargo qemu进行编译，显示了如下错误。
`
➜  [/home/wynn/Desktop/codes/rustsbi-qemu] git:(main) cargo qemu     
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/xtask qemu`
xtask: mode: Debug
   Compiling rustsbi v0.2.0-alpha.8
error: cannot find macro `asm` in this scope
  --> /home/wynn/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/rustsbi-0.2.0-alpha.8/src/privileged.rs:30:15
   |
30 |         () => asm!("
   |               ^^^
   |
   = note: consider importing this macro:
           core::arch::asm
`
因此，我认为是rustsbi v0.2.0-alpha.8导致的编译错误。
这是我使用的toolchain 的情况：
`➜  [/home/wynn/Desktop/codes/rustsbi-qemu] git:(main) rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/wynn/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2018-09-18-x86_64-unknown-linux-gnu
nightly-2019-07-15-x86_64-unknown-linux-gnu
nightly-2020-05-01-x86_64-unknown-linux-gnu
nightly-2020-06-04-x86_64-unknown-linux-gnu
nightly-2020-06-27-x86_64-unknown-linux-gnu
nightly-2021-10-15-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

riscv64imac-unknown-none-elf
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by '/home/wynn/Desktop/codes/rustsbi-qemu/rust-toolchain.toml')
rustc 1.59.0-nightly (475b00aa4 2021-12-24)`

奇怪的是，我在rustsbi的仓库下（https://github.com/rustsbi/rustsbi/）对rustsbi的最新版本0.2.0-alpha.9进行编译不会报错。
`
➜  [/home/wynn/Desktop/codes/rustsbi] git:(master) cargo build --target riscv64imac-unknown-none-elf

   Compiling memchr v2.4.1
   Compiling regex-syntax v0.6.25
   Compiling lazy_static v1.4.0
   Compiling nb v1.0.0
   Compiling bit_field v0.10.1
   Compiling void v1.0.2
   Compiling bare-metal v1.0.0
   Compiling nb v0.1.3
   Compiling embedded-hal v0.2.6
   Compiling aho-corasick v0.7.18
   Compiling regex v1.5.4
   Compiling riscv-target v0.1.2
   Compiling riscv v0.7.0
   Compiling rustsbi v0.2.0-alpha.9 (/home/wynn/Desktop/codes/rustsbi)
    Finished dev [unoptimized + debuginfo] target(s) in 6.48s
`
并且编译rustsbi使用的toolchain和编译rustsbi-qemu时使用的toolchain相同：
`
➜  [/home/wynn/Desktop/codes/rustsbi] git:(master) rustup show                                      
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/wynn/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2018-09-18-x86_64-unknown-linux-gnu
nightly-2019-07-15-x86_64-unknown-linux-gnu
nightly-2020-05-01-x86_64-unknown-linux-gnu
nightly-2020-06-04-x86_64-unknown-linux-gnu
nightly-2020-06-27-x86_64-unknown-linux-gnu
nightly-2021-10-15-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

riscv64imac-unknown-none-elf
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.59.0-nightly (475b00aa4 2021-12-24)
`

**Comment by luojia65** [comment]
核心问题在最近的1.59.0 rust把asm宏稳定了，移动了它的位置。目前的rustsbi还在预览版，预计ptr_metadata的事情解决后，rustsbi就可以在stable rust下编译了
