### ISSUE TITLE
使用cargo qemu进行build时报错

### ISSUE THREAD

**Issue by leo-frank** [rustsbi/rustsbi-qemu#11]
我在使用cargo qemu进行编译，显示了如下错误。
![image](https://user-images.githubusercontent.com/47302141/147375662-29f6f24c-ddf4-4f80-a354-50d42a8882ce.png)
因此，我认为是rustsbi v0.2.0-alpha.8导致的编译错误。
这是我使用的toolchain 的情况：
![image](https://user-images.githubusercontent.com/47302141/147375666-313cf0a0-7ad2-4a23-b5ed-a193d41e78eb.png)
奇怪的是，我在rustsbi的仓库下（https://github.com/rustsbi/rustsbi/） 
对rustsbi的最新版本0.2.0-alpha.9进行编译不会报错。
![image](https://user-images.githubusercontent.com/47302141/147375688-e88ed04b-0bd2-4e69-b207-2aa79eeef889.png)
并且编译rustsbi使用的toolchain和编译rustsbi-qemu时使用的toolchain相同：
![image](https://user-images.githubusercontent.com/47302141/147375652-c2b9017e-3553-4343-a6d9-34f8e21a165f.png)

看上去问题 的根源应该是最新版本的toolchain不太适配rustsbi  v0.2.0-alpha.8导致的编译错误。

**Comment by luojia65** [comment]
核心问题在最近的1.59.0 rust把asm宏稳定了，移动了它的位置。目前的rustsbi还在预览版，预计ptr_metadata的事情解决后，rustsbi就可以在stable rust下编译了（届时发布0.2.0正式版）

**Comment by leo-frank** [comment]
感谢！
