### ISSUE TITLE
rustsbi下字符显示异常

### ISSUE THREAD

**Issue by yfblock** [rustsbi/rustsbi-qemu#24]
![image](https://user-images.githubusercontent.com/14835777/170195285-e3fab94e-d0dd-4080-9a68-4f26eb179bf1.png)

可以看到对于某些字符重复发送导致格式异常和乱码
同样在opensbi下无此问题
下附opensbi图
![image](https://user-images.githubusercontent.com/14835777/170195093-2815096c-2c89-4488-b45a-49c6734a4ddf.png)

**Comment by luojia65** [comment]
opensbi是固定使用一个核启动的，这种做法无法运用多核的优势，效率较低。这个问题应该是ascii颜色字符的输出没有行锁导致的，请在内核中编写多核友好的启动代码。

**Comment by yfblock** [comment]
感谢 目前已经解决
