### ISSUE TITLE
关于非法指令的转发行为

### ISSUE THREAD

**Issue by yztz** [rustsbi/rustsbi-qemu#26]
在现有的处理中：
https://github.com/rustsbi/rustsbi-qemu/blob/96704cf4373b9eb804145268862ba92700e46b27/rustsbi-qemu/src/feature/transfer_trap.rs#L23
仅仅设置`SPP`为S态似乎有些草率。比如在xv6中，若是在用户态触发了非法指令异常，那么在异常处理函数中会判断该异常是否来自于用户态：
```c
if((r_sstatus() & SSTATUS_SPP) != 0){
  panic("usertrap: not from user mode");
}
```
若按上述设置，那么将会触发panic，这对于debug来说颇具误导性...

比较合适的设置方法应该是根据现有的MPP来设置SPP：
```rust
// 设置中断位
if ctx.mstatus.mpp() == MPP::User {
    mstatus::set_spp(SPP::User);
} else {
    mstatus::set_spp(SPP::Supervisor);
}
    
mstatus::set_mpp(MPP::Supervisor);
```

**Comment by luojia65** [comment]
感谢！这应该是一个实现中出现的错误，是需要修复的。我会等项目重构结束后注意这个问题

**Comment by YdrMaster** [comment]
转发函数已经改了，但其实现在是直接把非法指令也代理掉了，没有做模拟
