### ISSUE TITLE
在Ubuntu物理机和WSL 上行为不一致

### ISSUE THREAD

**Issue by 2catycm** [rustsbi/rustsbi-qemu#29]
您好！
我正在尝试跑通rcore。
按照 http://rcore-os.cn/rCore-Tutorial-Book-v3/chapter0/5setup-devel-env.html 里的描述，可以正常在WSL和物理机上跑通rcore。
然而，我注意到有一个rcore的实验指导，专门为了做实验的同学设计的，这里面的代码和tutorial稍有不同，我尝试跑通[实验指导三：虚拟内存](http://rcore-os.cn/rCore-Tutorial-deploy/docs/lab-3/guide/part-1.html)的时候的时候，出现了以下奇怪的情况:

物理机+opensbi(qemu参数改为default): 正常运行！
物理机+rustsbi2.2.0： 运行失败！ 具体来说，在虚拟内存开启之后(mm::init()之后)，println宏无法打印变量的值，此时PC不知道跑哪去了，再也没有输出了！
WSL+opensbi： 所有章节的rcore都运行失败！（rcore指的是实验指导的rcore，不是tutorial的rcore）
WSL+rustsbi: 没有虚拟内存的章节的rcore可以正常运行，但是开启了虚拟内存章节的rcore运行失败！

**Comment by YdrMaster** [comment]
我们不知道和 OpenSBI 的区别是什么，而且我们希望没有区别。这句话有两方面含义，换句话说，既然 rustsbi 和 opensbi 遵循同样的标准（目前是 SBI SPEC v1.0.0），就应该表现出一致的行为；且不一致的行为应该视为 bug（但可能是 opensbi 或 rustsbi 的 bug，也可能是标准的描述不够明确）。

具体来说，rustsbi-qemu 这个项目本身做了 windows+ubuntu 适配，理论上说，它在所有 qemu 上都应该有一致的表现，不仅包括同一份 qemu 源码的不同编译产物，甚至应该包括任何 qemu（至少保证 6.1 以上）。

但是，仅就你目前的描述，很难判断问题出在哪里。近期这个项目经历了一些重构，中间版本不一定是正确的，也许你可以试着编译这个项目的 pr #28 所在的分支，看看有没有不同的结果。另外，应该关注实验指导与正常的教程有何不同。

**Comment by YdrMaster** [comment]
@2catycm 嗨，最近有什么进展吗

**Comment by 2catycm** [comment]
嗨，感谢你之前的回复。我还在理解rcore的代码，我注意到新版的rcore里面虚拟内存管理和以前的ucore和rcore不一样，以前都是entry.asm里面把虚拟地址0xFF..FF80200000映射为0x8020000，汇编中直接改页表，现在新版是在rust代码里面改的，而且好像去掉了奇怪的FF，改成了直接是恒等映射。
tranpoline那一部分我还没理解完全。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月31日(周日) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rustsbi/rustsbi-qemu] 在Ubuntu物理机和WSL 上行为不一致 (Issue #29)




 
@2catycm 嗨，最近有什么进展吗

**Comment by YdrMaster** [comment]
@2catycm 经典问题，可以看[我的笔记](https://github.com/YdrMaster/notebook/blob/main/zCore/20220418-difference-of-memory-between-zcore-and-rcore-v3/doc.md)

**Comment by YdrMaster** [comment]
似乎没有进一步的问题了？我先关了，也可以加微信聊，rcore 群里可以找到我们

**Comment by 2catycm** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月8日(周一) 上午9:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rustsbi/rustsbi-qemu] 在Ubuntu物理机和WSL 上行为不一致 (Issue #29)




 
似乎没有进一步的问题了？我先关了，也可以加微信聊，rcore 群里可以找到我们
