### ISSUE TITLE
qemu@7.1.0以上版本没有任何输出

### ISSUE THREAD

**Issue by ericliuhusky** [rustsbi/rustsbi-qemu#48]
qemu@7.2.0
branch: main
run: cargo qemu
ouput: none

回退qemu@7.1.0输出正常
macOS使用brew安装旧版本qemu参考https://shockerli.net/post/homebrew-install-formula-specific-version/

**Comment by luojia65** [comment]
你好！已经计划在#45里修复了，会发布下一个新版本。这次问题主要是qemu内部修改了串口输出的设备名称导致的，新版本会同时识别不同版本qemu的设备名称，这件事情我会和qemu的开发者继续聊一聊。感谢！

**Comment by luojia65** [comment]
主线上已经修好了
