### ISSUE TITLE
或许可以考虑将test-kernel独立成一个新的项目？

### ISSUE THREAD

**Issue by retrhelo** [rustsbi/rustsbi-qemu#5]
注意到作为测试用例的test-kernel目前是作为该项目以及rustsbi-k210项目的一部分存在的。考虑到其作为测试用例而言对这两个sbi实现具有普适性，是否可以将test-kernel独立出来？这样还可以方便其他的SBI实现使用其作为测试用例。

**Comment by duskmoon314** [comment]
看上去这是一个好的思路，不过最近主维护者 @luojia65 似乎忙于其他事物

**Comment by duskmoon314** [comment]
询问了一下，test-kernel 根据项目可能需要增补一些平台相关的测试。如果考虑独立出来的话，需要设计一下架构，看看如何便于扩展。

**Comment by retrhelo** [comment]
我觉得test-kernel只要能够测试SBI调用是否正确就好了，基本上应该可以做到平台无关的。而且为了能够在不同平台和不同的SBI实现上使用，我觉得也不应该把test-kernel做得太平台相关。

**Comment by retrhelo** [comment]
其实我觉得可以先把仓库建起来，把现在的代码扔到仓库里面去，后面我们再慢慢贡献代码。

**Comment by SKTT1Ryze** [comment]
这个其实没太必要，测试内核就那么点代码量，没必要占用组织的一个仓库。该组织的仓库基本上都应该为rustsbi和rustsbi的各个平台下的实现预留的。

**Comment by luojia65** [comment]
这样做也可以，看后面项目如何发展了

**Comment by YdrMaster** [comment]
test-kernel 的 test 部分现在已经挪动到 [sbi-testing](https://github.com/rustsbi/sbi-testing)。我希望 test-kernel 是一个库的组合体，不知道是否满足你的期望？

**Comment by retrhelo** [comment]
> test-kernel 的 test 部分现在已经挪动到 [sbi-testing](https://github.com/rustsbi/sbi-testing)。我希望 test-kernel 是一个库的组合体，不知道是否满足你的期望？

这个仓库看上去很不错。用库的形式，通过API允许测试者根据需要构建测试，这应该会是一个更好的形式。
