### ISSUE TITLE
请教一下是怎么加载并启动内核的，相关代码是哪部分？🙏

### ISSUE THREAD

**Issue by holicc** [rustsbi/rustsbi-qemu#52]

**Comment by YdrMaster** [comment]
qemu 的内核是用 `-kernel` 传的，所以没有加载内核的代码。物理硬件需要可以参考 [rustsbi-qemu 的 spl 部分](https://github.com/rustsbi/rustsbi-d1/tree/main/spl)。

启动就是直接跳转到加载好的内核入口，由于一些具体的原因，这部分写的比较复杂，主要在[这里](https://github.com/rustsbi/rustsbi-qemu/blob/e693a23730c9c17ff44561e401d0988e3c5d47d5/rustsbi-qemu/src/main.rs#L215)。
