### ISSUE TITLE
QEMU 8.0.0: call `SBI_SHUTDOWN` with failure

### ISSUE THREAD

**Issue by TD-Sky** [rustsbi/rustsbi-qemu#53]
## Key code

https://github.com/rcore-os/rCore-Tutorial-v3/blob/ch5/os/src/sbi.rs

## Expected

**rCore** should shutdown before `unreachable!()`.

## Actual

**rCore** panicked at `unreachable!()` and shutdown recursively infinitely.

**Comment by YdrMaster** [comment]
如果更新 rustsbi-qemu 呢？就是用这个 repo 重新编译一个放进去。

**Comment by TD-Sky** [comment]
重新编译了 rustsbi-qemu 放到 https://github.com/rcore-os/rCore-Tutorial-v3/tree/ch5 的 bootloader 下，然后成功关机了。

我是不是应该在自己的rcore内通过[sbi-rt](https://crates.io/crates/sbi-rt)调用sbi？因为我更换自己的bootloader之后，依旧无法关机。

**Comment by YdrMaster** [comment]
这一系列问题就是因为我们决定在这几个版本里不支持 legacy 调用，而 rcore 那边从项目中迁移调用远远慢于 sbi 的更新（或者不如说是在我们的支持政策下不得不更新……）。

总之，只要是使用非 legacy 的调用就不会有问题，我只能说我推荐用 sbi-rt，比手写汇编方便。

**Comment by YdrMaster** [comment]
如果解决了可以关闭 issue 🙇‍
